package com.wishare.finance.infrastructure.conts;

import com.wishare.starter.interfaces.ErrMsg;

/**
 * 异常枚举常量
 */
public enum ErrorMessage implements ErrMsg {

    DISABLE_STATE_EXCEPTION("启用禁用状态异常"),
    DISABLE_PARAM_ERROR("启用禁用参数不正确"),

    STATUTORY_BODY_CODE_EXISTS("法定单位编码已存在"),
    STATUTORY_BODY_NAME_EXISTS("法定单位名称已存在"),
    STATUTORY_BODY_NO_EXISTS("法定单位不存在"),

    STATUTORY_BODY_ACCOUNT_NO_EXISTS("银行账户不存在"),
    STATUTORY_BODY_ACCOUNT_EXISTS("银行账户已存在"),
    STATUTORY_BODY_ACCOUNT_NAME_EXISTS("银行账户名称已存在"),
    STATUTORY_BODY_ACCOUNT_BASIC_TYPE_EXISTS("法定单位下已存在一个基本户"),

    COST_CENTER_CODE_EXISTS("成本中心编码已存在"),
    COST_CENTER_NAME_EXISTS("成本中心名称已存在"),
    COST_CENTER_NO_EXISTS("成本中心不存在"),

    ACCOUNT_BOOK_CODE_EXISTS("账簿编码已存在"),
    ACCOUNT_BOOK_NO_EXISTS("账簿不存在"),
    ACCOUNT_BOOK_EXISTS("账簿已存在"),
    ACCOUNT_BOOK_MAP_ERROR("账簿映射组合存在重复项，请确认后再提交"),

    //发票相关异常提示
    INVOICE_BOOK_NO_EXISTS("票本不存在"),
    INVOICE_BOOK_HAS_RECEIVE("当前票本内的票据已被领用,无法删除"),

    INVOICE_RECEIVE_NO_EXISTS("发票领用不存在"),
    INVOICE_NOT_EXISTS("发票不存在"),
    INVOICE_RECORD_REPEAT("请勿重复请求认领发票"),
    RE_VOID_RECEIPT("请勿重复请求作废收据"),
    INVOICE_QUANTIT_MORE("发票领用数量超额异常"),
    INVOICE_PUSH_PHONE_ERROR("发票推送手机号不存在"),
    INVOICE_PUSH_EMAIL_ERROR("发票推送邮箱不存在"),

    FLOW_DETAIL_NOT_EXIST("流水单不存在"),
    FLOW_NUMBER_EXIST("流水号已存在"),
    FLOW_OUR_ACCOUNT_NOT_SAME("流水本方账户信息不一致"),
    FLOW_OPPOSITE_ACCOUNT_IS_EMPTY("对方账户不能为空"),
    FLOW_OPPOSITE_NAME_IS_EMPTY("对方名称不能为空"),
    FLOW_OPPOSITE_BANK_IS_EMPTY("对方开户行不能为空"),
    FLOW_OUR_ACCOUNT_IS_EMPTY("本方账户不能为空"),
    FLOW_OUR_NAME_IS_EMPTY("本方名称不能为空"),
    FLOW_TRADING_PLATFORM_IS_EMPTY("交易平台不能为空"),
    FLOW_OUR_BANK_IS_EMPTY("本方开户行不能为空"),
    FLOW_SETTLE_AMOUNT_IS_EMPTY("交易金额不能为空"),
    FLOW_SETTLE_AMOUNT_NOT_LEGAL("交易金额不合法，请保证小数点后最多两位小数"),
    FLOW_CLAIM_AMOUNT_NOT_SAME("流水金额与票据金额不一致"),
    FLOW_CLAIM_RECORDS_NOT_EXIST("流水认领记录不存在"),
    FLOW_CLAIM_REVOKED_FAIL("流水认领撤销失败"),
    INVOICE_CLAIMED("【{0}】票据已被认领"),
    FLOW_CLAIMED("【{0}】流水已被认领"),
    FLOW_SUSPEND("【{0}】流水已被挂起"),
    FLOW_SYNC_DELETE_FAIL("不可删除同步的流水"),
    FLOW_CLAIMED_DELETE_FAIL("不可删除已认领的流水"),
    FLOW_APPROVE_DELETE_FAIL("不可删除审核中的流水"),
    RECONCILE_RULE_EXIST("对账规则已存在"),
    RECONCILE_RULE_TIME_NOT_EXIST("对账规则执行时间格式不正确"),
    RECONCILE_RULE_NOT_EXIST("对账规则不存在"),
    RECONCILE_RULE_IS_RUNNING("对账规则正在执行中"),
    RECONCILE_RULE_NOT_DIMENSION("必须设置一个对账维度"),
    RECONCILE_NOT_DATA("暂无可对账数据"),
    RECONCILE_RUNNING("对账中，请勿重复操作"),
    RECONCILE_DISABLED("对账规则未启用"),
    RECONCILE_MODE_NOT_SUPPORT("不支持的对账模式"),
    RECONCILE_TYPE_NOT_SUPPORT("不支持的对账类型"),
    RECONCILE_DETAIL_NOT_EXIST("对账信息不存在"),
    RECONCILE_DETAIL_PARAM("入参billNo为空"),
    RECONCILE_DETAIL_HAVE_VOUCHER_BILL_NO("请先删除关联的报账单，再解除认领"),
    RECONCILE_DETAIL_RESULT_ERROR("交易对账状态非「已核对」"),
    RECONCILE_DETAIL_FLOW_IS_NULL("关联的流水id列表"),
    RECONCILE_DETAIL_FLOW_IS_PUSH("解除对账失败，该收款单已生成对账核销报账单并已推送至NC65。"),
    RECONCILE_DETAIL_FLOW_NO_PUSH("解除对账失败，该收款单已生成对账核销报账单，请先删除报账单。"),
    RECONCILE_DETAIL_FLOW_RECORD_IS_NULL("流水认领记录不存在"),
    XXL_JOB_CRON_RULE_ERROR("时间规则错误"),
    XXL_JOB_PARAMS_ERROR( "xxl-job参数错误"),
    XXL_JOB_TASK_ID_ERROR( "xxl-job任务id错误"),
    XXL_JOB_EXECUTOR_ERROR( "xxl-job未找到执行器"),
    XXL_JOB_RESPONSE_ERROR( "xxl-job响应错误"),
    XXL_JOB_PWD_ERROR( "xxl-job账号密码为空"),

    BILL_ADD_LENGTH_ERROR("批量新增账单数据条数不正确，大小区间为[1,1000]"),
    BILL_TYPE_NOT_SUPPORT("不支持的账单类型"),
    BILL_METHOD_NOT_SUPPORT("不支持的计费方式"),
    GATHER_TYPE_NOT_SUPPORT("不支持的收款类型"),
    BILL_CHARGE_METHOD_NOT_SUPPORT("不支持的计费方式"),
    BILL_IS_APPROVED("账单已审核"),
    BILL_APPROVE_STATE_NOT_SUPPORT("不支持的审核状态"),
    BILL_APPROVE_NOT_SUPPORT("非初始化审核，不存在审核记录"),
    BILL_APPROVE_NOT_EXIST("审核记录不存在"),
    BILL_SETTLE_STATE_NOT_SUPPORT("不支持的结算状态"),
    BILL_APPROVE_OPERATE_TYPE_NOT_SUPPORT("不支持的审核操作类型"),
    BILL_APPROVE_RECORD_NOT_EXIST("账单审核记录不存在"),
    BILL_APPLY_PARAM_ERROR("申请类型与申请参数不一致"),
    BILL_APPLY_DEDUCTION_ERROR("已核对的账单不允许减免或调低操作"),
    BILL_RECONCILE_APPLY_DEDUCTION_ERROR("部分核对的账单调低或减免的金额不可涉及到实收金额部分"),
    BILL_APPLY_REVERSE_ERROR("对账成功后的账单不允许冲销操作哦"),
    BILL_APPLY_BATCH_TYPE_ERROR("批量申请仅支持账单作废"),
    BILL_IS_APPROVING("账单审核中，不允许操作"),
    BILL_IS_OPERATING("账单{0}，不允许操作"),
    NEGATIVE_BILL_NO_OPERATE("存在负数金额的账单，不允许该操作"),
    BILL_NO_IS_OPERATING("账单{0}{1}，不允许操作"),
    BILL_DEAPPROVE_STATE_NOT_SUPPORT("{0}状态下，不允许反审核"),



    BILL_INVALID_STATE_NOT_SUPPORT("不满足作废条件（未结算且未开票），不允许作废"),
    BILL_BATCH_QUERY_ERROR("检索条件不能为空"),
    BILL_BATCH_ERROR("检索条件或账单id不能同时为空"),
    BILL_ADJUST_NOT_EXIST("账单调整记录不存在，请重新申请调整"),
    BILL_ADJUST_UNIT_PRICE_NOT_NULL("调整单价不能为空"),
    BILL_ADJUST_AREA_NOT_NULL("调整面积不能为空"),
    BILL_ADJUST_TAX_RATE_NOT_NULL("调整税率不能为空"),
    BILL_ADJUST_OVERDUE_RATE_NOT_NULL("违约金比率不能为空"),
    BILL_BREAK_CONTRACT_START_METHOD("延期天数不能为空"),
    BILL_END_TIME("账单结束时间为空"),
    BILL_RECEIVABLE_DATE("账单应收日为空"),
    BILL_LATE_DAYS("违约金比率不能为空"),
    BILL_ADJUST_AMOUNT_NOT_NULL("调整金额不能为空"),
    BILL_ADJUST_NUM_NOT_NULL("调整数量不能为空"),
    BILL_ADJUST_STATE_ERROR("账单{0}，无法调整"),
    BILL_ADJUST_WAY_ERROR("{0}状态下，调整方式【{1}】不允许调整"),
    BILL_ADJUST_WAY_NOT_SUPPORT("不支持的调整方式"),
    BILL_ADJUST_TYPE_NOT_SUPPORT("不支持的调整类型"),
    BILL_ADJUST_REASON_NOT_SUPPORT("不支持的调整原因"),
    BILL_ADJUST_AMOUNT_DEDUCTIBLE_ERROR("调整后的账单金额不能小于应收减免金额"),
    BILL_ADJUST_AMOUNT_DISCOUNT_ERROR("调整后的账单应收金额不能小于实收减免金额"),
    BILL_ADJUST_SETTLE_AMOUNT_ERROR("调整后的账单实收金额不能小于0"),
    BILL_ADJUST_RECEIVABLE_AMOUNT_ERROR("调整后的账单应收金额不能小于0"),
    BILL_ADJUST_UNIT_PRICE_ERROR("调整后的单价金额不能小于0"),
    BILL_ADJUST_CHARGE_ERROR("调整转预收费项错误"),
    BILL_NOT_EXIST("账单不存在"),
    BILL_NOT_SETTLE("该批次存在已结算状态的账单"),
    BILL_SETTLEING("该批次存在结算中状态的账单"),
    BILL_NOT_SETTLE_HAS_CARRYOVER("该批次存在已结转状态的账单"),
    BILL_NOT_SETTLE_NO_APPROVE("该批次存在未审核状态的账单"),
    BILL_CARRYOVER_TYPE_NOT_SUPPORT("结转方式不支持"),
    BILL_CARRYOVER_ADVANCE_NOT_SUPPORT("是否结转预收方式不支持"),
    BILL_CARRYOVER_NOT_EXIST("账单结转记录不存在"),
    BILL_CARRYOVER_TARGET_NOT_EXIST("被结转账单[{0}]不存在"),
    BILL_CARRYOVER_AMOUNT_NO_ENOUGH("账单可结转余额不足"),
    BILL_CARRYOVER_AMOUNT_OUT_MEMORY("账单结转额度必须小于等于可结转额度（可结转额度=结算金额 - 已结转金额）"),
    BILL_CARRYOVER_STATE_NOT_SUPPORT("{0}状态下，不允许结转"),
    BILL_DELETE_ERROR("反审核的账单不允许删除"),
    BILL_NOT_DEDUCT("账单状态不支持扣款"),
    BILL_CHARGE_NOT_DEDUCT("账单费项类型为押金收费类型才支持扣款"),
    BILL_MONEY_NOT_DEDUCT("金额已超出可扣款额度"),

    BILL_ADVANCE_START_TIME_AFTER_END_TIME("预收导入账单开始时间大于结束时间"),
    UNIFIED_ACCOUNTING_REPEAT("请勿重复入账"),
    BILL_START_TIME_AFTER_END_TIME("账单开始时间大于结束时间"),
    BILL_SETTLE_AMOUNT_ERROR("账单结算金额不能大于应收金额 + 违约金金额 - 减免金额 + 退款金额 - 上次结算金额"),
    BILL_SETTLE_CHANNEL_NOT_SUPPORT("结算渠道不支持"),
    BILL_SETTLE_WAY_NOT_SUPPORT("结算渠道不支持"),
    BILL_SETTLE_STATE_ERROR("账单处于{0}状态下，不允许被结算或被结转"),
    BILL_REFUND_AMOUNT_ERROR("退款异常：退款金额大于结算金额"),

    BILL_HAND_STATE_NOT_SUPPORT("不支持的交账状态"),
    BILL_ON_ACCOUNT_STATE_NOT_SUPPORT("不支持的挂账状态"),
    BILL_INVOICE_STATE_NOT_SUPPORT("不支持的开票状态"),
    BILL_PAY_STATE_NOT_SUPPORT("不支持的支付状态"),
    BILL_FREEZE_TYPE_NOT_SUPPORT("不支持的冻结类型"),
    BILL_REVERSE_STATE_NOT_SUPPORT("不支持的冲销状态"),

    BILL_REFERENCE_STATE_NOT_SUPPORT("不支持的引用状态"),
    BILL_RECONCILE_STATE_NOT_SUPPORT("不支持的对账状态"),
//    BILL_INVOICE_AMOUNT_ERROR("开票金额不能大于实际收款金额（结算金额-退款金额-结转金额）"),
    BILL_INVOICE_AMOUNT_ERROR("开票金额不能大于应收金额"),

    BILL_IS_REVERSE("账单已冲销"),
    BILL_REVERSE_REPEAT("请勿重复冲销"),
    BILL_ON_ACCOUNT_NOT_SUPPORT("不支持挂账的账单类型"),
    BILL_HAS_NO_INVOICE("账单未开票"),

    VOUCHER_NOT_EXIST("凭证不存在"),
    VOUCHER_RULE_EXECUTE_TYPE_NOT_HAND("规则的执行类型不是手动推凭"),
    VOUCHER_RULE_NOT_EXIST("凭证规则不存在或禁用状态"),

    BILL_RULE_NOT_EXIST("推单规则不存在或禁用状态"),
    BILL_RULE_SCHEDULE_ERROR("推单规则-推单模式为定时推送时定时规则不能为空"),
    BILL_RULE_NAME_EXIST("相同名称的推单规则已存在"),
    BILL_RULE_IS_RUNNING("推单规则运行中，请勿操作"),
    BILL_RULE_IS_DISABLED("推单规则已被禁用"),
    VOUCHER_RULE_NAME_EXIST("相同名称的凭证规则已存在"),
    VOUCHER_RULE_IS_DISABLED("凭证规则已被禁用"),
    VOUCHER_RULE_IS_RUNNING("凭证规则运行中，请勿操作"),
    VOUCHER_RULE_SCHEDULE_ERROR("凭证规则-推凭模式为定时推送时定时规则不能为空"),
    VOUCHER_RULE_EXECUTE_STATE_NOT_SUPPORT("凭证规则运行状态不支持"),
    VOUCHER_RULE_CONDITION_NOT_EXIST("凭证规则过滤条件不能为空"),
    VOUCHER_RULE_CONDITION_TYPE_NOT_SUPPORT("凭证规则过滤条件类型不支持"),
    VOUCHER_RULE_CUSTOMER_TYPE_NOT_SUPPORT("凭证业务单据收费对象类型不支持"),
    VOUCHER_RULE_BUSINESS_SCENARIO_NOT_SUPPORT("凭证规则筛选条件业务场景不支持"),
    VOUCHER_RULE_PAY_WAY_NOT_SUPPORT("凭证规则结算方式不支持"),
    VOUCHER_RULE_PUSH_MODE_NOT_SUPPORT("凭证规则-推凭模式不支持"),
    VOUCHER_RULE_CONDITION_METHOD_NOT_SUPPORT("凭证规则过滤方式不支持"),
    VOUCHER_RULE_LOGIC_NOT_EXIST("凭证规则分录逻辑不存在，请设置分录计算逻辑"),
    VOUCHER_RULE_LOGIC_TYPE_NOT_SUPPORT("凭证规则分录逻辑类型不支持"),
    VOUCHER_RULE_BOOK_MODE_NOT_SUPPORT("推凭账簿模式不支持"),
    VOUCHER_RULE_STATE_NOT_SUPPORT("凭证规则运行状态不支持"),
    VOUCHER_RULE_CONDITION_ACCOUNT_BEFORE_NOT_EXIST("凭证规则未选择法定单位或者客商无法选择收/付款账户"),
    VOUCHER_MAKE_TYPE_NOT_SUPPORT("不支持的录制方式"),
    VOUCHER_TEMPLATE_TYPE_NOT_SUPPORT("不支持的凭证模板类型"),
    VOUCHER_BUSINESS_BILL_TYPE_NOT_SUPPORT("不支持的业务单据类型"),
    VOUCHER_SYSTEM_NOT_SUPPORT("不支持的凭证系统"),
    VOUCHER_TYPE_NOT_SUPPORT("不支持的凭证类型"),
    VOUCHER_EVENT_TYPE_NOT_SUPPORT("不支持的事件类型"),
    VOUCHER_ASSISTE_ITEM_NOT_SUPPORT("不支持的辅助核算类型"),
    BPM_VOUCHER_ASSISTE_ITEM_NOT_SUPPORT("不支持的BPM辅助核算值"),
    VOUCHER_AMOUNT_ERROR("凭证录制失败，借贷金额不一致"),
    VOUCHER_RUN_BUSINESS_ERROR("凭证规则运行失败，找到不到单据类型【{0}】，id={1}的单据信息"),
    VOUCHER_RUN_SCHEME_ERROR("凭证规则运行失败，找到不到指定核算方案"),
    VOUCHER_RUN_TEMPLATE_ENTRIES_ERROR("凭证规则运行失败，凭证模板分录错误"),
    VOUCHER_SCHEME_ADD_ERROR("新增凭证核算方案失败，请确认参数后重试"),
    VOUCHER_SCHEME_NOT_EXIST("凭证核算方案不存在"),
    VOUCHER_SCHEME_NAME_EXIST("核算方案名称不能重复"),
    VOUCHER_TEMPLATE_NAME_EXIST("模板名称不能重复"),
    VOUCHER_TEMPLATE_NOT_EXIST("凭证模板不存在"),
    VOUCHER_RULE_NOT_LINK_SCHEME("请先将凭证规则与核算方案关联"),
    VOUCHER_TEMPLATE_SUMMARY_TYPE_NOT_SUPPORT("凭证模板分录摘要类型不支持"),
    VOUCHER_RUN_REDUCE_ERROR("凭证规则运行失败，找不到已推凭过的应收单"),
    VOUCHERINFERENCE_NOT_EXIST("删除推凭记录未传递参数id"),
    VOUCHERINFO_OR_DETAIL_NOT_FOUND("未查询到符合条件的明细数据"),
    VOUCHERINFERENCE_DELETE_FAIL("删除推凭记录失败"),

    TAX_CATEGORY_EXISTS("税种已存在"),
    TAX_CATEGORY_NO_EXISTS("税种不存在"),
    TAX_CATEGORY_CODE_EXISTS("税种编码已存在"),
    TAX_CATEGORY_NAME_EXISTS("税种名称已存在"),
    TAX_CATEGORY_PARENT_NOT_EXIT("父税种id不存在"),
    TAX_CATEGORY_USED_BY_CHARGE_ITEM("税种下税率已被以下费项引用不可删除："),

    TAX_RATE_NO_EXISTS("税率不存在"),
    TAX_RATE_USED_BY_CHARGE_ITEM("税率已被以下费项引用不可删除："),
    TAX_RATE_ERROR("请正确填写税率"),
    TAX_RATE_CONTENT_ERROR("税率填写有误"),
    TAX_RATE_NOT_FIND_ERROR("未找到税率信息"),
    TAX_ITEM_NOT_EXIST("税目不存在"),
    TAX_ITEM_GOODS_NOT_EXIST("税收商品信息不存在"),
    TAX_ITEM_CODE_EXIST("税目编码已存在"),
    TAX_ITEM_GOODS_NAME_EXIST("税收商品名称已存在"),
    TAX_CHARGE_ITEM_RELATION_OTHER("费项已关联其他税目"),
    TAX_CHARGE_ITEM_GOODS_RELATION_OTHER("费项已关联其他税收商品"),

    CHARGE_NAME_EXIST("费项名称已存在"),
    CHARGE_CODE_EXIST("费项编码已存在"),
    CHARGE_EXIST_SUB("费项存在子节点"),
    CHARGE_NOT_EXIST("费项不存在"),
    CHARGE_OVERDUE_EXIST("违约金费项已存在"),
    CHARGE_BUSINESS_FLAG_EXIST("业务标识费项已存在"),
    CHARGE_NOT_ADD("费项已是末级，不能新增子节点"),
    CHARGE_BUSINESS_SEGMENT_LIMIT("只有末级费项可以设置业务板块"),

    CHARGE_PARENT_NOT_ADD("父费项已是末级，不能新增子节点"),
    CHARGE_NOT_UPDATE_LAST_LEVEL("费项存在子级，不能修改为末级"),
    CHARGE_CODE_MAX_TWO("分成费项最大不能超过两个"),
    CHARGE_CODE_MAX_LENGTH("费项编码长度不能超过20位"),

    GATHER_DETAIL_INVOICE_EXIST("该收款明细开票中，请勿重复开票"),

    SUBJECT_SYSTEM_NAME_OR_CODE_EXIST("科目体系名称或编码已存在"),
    SUBJECT_SYSTEM_NAME_EXIST("科目体系名称已存在"),
    SUBJECT_SYSTEM_CODE_EXIST("科目体系编码已存在"),
    SUBJECT_SYSTEM_NOT_EXIST("科目体系不存在"),
    SUBJECT_SYSTEM_EXIST_SUBJECT("科目体系存在科目"),
    SUBJECT_NAME_EXIST("科目名称已存在"),
    SUBJECT_NOT_EXIST("科目不存在"),
    SUBJECT_PARENT_NOT_EXIST("父科目不存在"),
    SUBJECT_EXCEED_MAX_LEVEL("科目超过最大层数"),
    SUBJECT_EXIST_SUB_SUBJECT("当前科目存在子科目,无法更新"),
    SUBJECT_CODE_EXIST("科目编码已存在"),
    SUBJECT_CATEGORY_PARENT_NOT_EXIST("父科目类型不存在"),
    SUBJECT_CATEGORY_EXIST("科目类型名称已存在"),
    SUBJECT_CATEGORY_NOT_EXIST("科目类型不存在"),
    SUBJECT_CATEGORY_EXCEED_LEVEL("科目类别超过最大层数"),
    SUBJECT_SYSTEM_RELATED_STATUTORY("科目体系已关联法定单位，不可删除"),

    SUBJECT_MAP_RULES_NOT_FOUND("科目映射规则不存在或已被删除"),

    PAYMENT_PRE_TRANSACT_NOT_EXIST("预支付信息不存在"),
    PAYMENT_PRE_TRANSACT_TIME_NOT_NULL("支付时间不能为空"),
    PAYMENT_PRE_TRANSACT_WAY_NOT_NULL("支付方式不能为空"),
    PAYMENT_PRE_TRANSACT_CHANNEL_NOT_NULL("支付渠道不能为空"),
    PAYMENT_PRE_TRANSACT_AMOUNT_ERROR("预支付金额与实际应缴不符"),
    PAYMENT_PRE_TRANSACT_PAYING("存在支付中账单，请勿重复操作"),
    PRE_GATHER_OPERATING("收款单正在操作中，请勿重复操作"),

    PAYMENT_ACCOUNT_NOT_EXIST("付款账号不存在，请前往财务中台配置收款账号"),
    PAYMENT_ACCOUNT_MULTI("收款账号存在多个法定单位使用，请确认财务中台配置是否有误"),
    PAYMENT_PRE_BILL_LOCK_TIME("过期时间不能小于当前时间"),

    PAYMENT_CHANNEL_NOT_SUPPORT("支付渠道{0}暂不支持"),
    PAYMENT_SB_NOT_NULL("法定单位id和编码二选一条件不能同时为空"),
    PAYMENT_COST_NOT_NULL("成本中心id和编码二选一条件不能同时为空"),
    PAYMENT_CHARGE_ITEM_NOT_NULL("费项id和编码二选一条件不能同时为空"),

    PAYMENT_GP_TYPE_NOT_SUPPORT("不支持的收付类型"),
    PAYMENT_TYPE_NOT_SUPPORT("交易类型不支持"),
    PAYMENT_INVOICE_STATE_NOT_SUPPORT("交易发票状态不支持"),
    PAYMENT_VOUCHER_STATE_NOT_SUPPORT("交易推凭状态不支持"),
    VOUCHER_APPROVE_STATE_NOT_SUPPORT("审批流程状态不支持"),
    ACCOUNT_CLOSE_STATE_NOT_SUPPORT("关账状态不支持"),
    PAYMENT_STATE_NOT_SUPPORT("交易状态不支持"),
    PAYMENT_TRADING("交易中，请勿重复操作"),
    PAYMENT_PAY_CHANNEL_NOT_SUPPORT("结算渠道暂不支持"),
    PAYMENT_TRADED("当前订单交易已完成，请勿重复操作"),
    PAYMENT_TRADED_NOT_EXIST("交易不存在"),
    PAYMENT_STATE_ERROR("当前交易状态不支持操作"),

    ACCOUNT_HAND_BILL_NOT_EXIST("交账账单不存在"),
    ACCOUNT_HAND_RULE_NOT_EXIST("交账规则不存在"),
    ACCOUNT_HAND_STATE_ERROR("账单未结算或未挂账，不允许交账"),


    REIMBURSE_CHARGE_ITEM_NOT_EXIST("报销费项不存在"),
    REIMBURSE_STATUTORY_BODY_NO_EXISTS("报销账簿未关联法定单位"),

    BUSINESS_UNIT_NO_EXISTS("业务单元不存在"),


    PAY_SOURCE_NOT_SUPPORT("支付来源不支持"),

    UPDATE_VOUCHER_DETAIL_FAIL("凭证明细修改失败"),
    VOUCHER_STATE_IS_NOT_UPDATE("凭证状态不支持修改"),

    SUP_CP_UNIT_ID_NOT_EXIST("上级收费单元id不能为空"),
    CLOSE_ACCOUNT_FAIL("关账失败，该会计期间已关账"),
    REVERSED_CLOSE_ACCOUNT_FAIL("反关账失败，该会计期间未关账"),

    PROCESS_CHARGE_SUBJECT_NOT_NULL("二级费项和科目信息不能同时为空"),
    PROCESS_PAY_SIZE_NOT_EQUAL("payBankInfos大小应与publicPayees或privatePayees大小相等"),

    PROCESS_APPLY_REPEAT("支付单已存在，请勿重复请求"),
    CHANNEL_TYPE_NOT_SUPPORT("服务商类型不支持"),
    RUN_BUSINESS_RULE_REPEAT("请勿重复运行报账规则"),

    CARRYOVER_BILL_NOT_EXIST("被结转账单已被删除"),
    ;

    private String errMsg;

    ErrorMessage(String errMsg) {
        this.errMsg = errMsg;
    }

    public String getErrMsg() {
        return errMsg;
    }

    @Override
    public String msg() {
        return errMsg;
    }
}
